# tests/test_routing_rules.py
"""
Unit-тесты для core/routing/rules.py — pure классы правил
RoutingRule / CidrRoutingRule / DomainRoutingRule / DeviceRoutingRule.
"""

import unittest

from core.routing.rules import (
    RoutingRule, CidrRoutingRule, DomainRoutingRule, DeviceRoutingRule,
    rule_from_dict,
    _valid_iface_name, _detect_family, _normalize_cidr,
)


class TestValidIfaceName(unittest.TestCase):

    def test_valid(self):
        for n in ("awg0", "wg0", "Wireguard0", "opkgtun0", "tun-1"):
            self.assertTrue(_valid_iface_name(n), n)

    def test_invalid(self):
        for n in ("", "a/b", "with space", "x" * 16,
                  "a@b", "i?face"):
            self.assertFalse(_valid_iface_name(n), n)


class TestDetectFamily(unittest.TestCase):

    def test_v4(self):
        self.assertEqual(_detect_family("10.0.0.0/24"), "v4")
        self.assertEqual(_detect_family("192.168.0.0/16"), "v4")

    def test_v6(self):
        self.assertEqual(_detect_family("2001:db8::/32"), "v6")
        self.assertEqual(_detect_family("::1/128"), "v6")

    def test_invalid(self):
        with self.assertRaises(ValueError):
            _detect_family("not-a-cidr")


class TestNormalizeCidr(unittest.TestCase):

    def test_already_normalized(self):
        self.assertEqual(_normalize_cidr("10.0.0.0/24"), "10.0.0.0/24")

    def test_single_ip_v4(self):
        # 1.2.3.4 без маски → /32
        self.assertEqual(_normalize_cidr("1.2.3.4"), "1.2.3.4/32")

    def test_single_ip_v6(self):
        self.assertEqual(_normalize_cidr("::1"), "::1/128")

    def test_strict_false(self):
        # 10.0.0.5/24 — некорректное strict=True, но нам OK
        self.assertEqual(_normalize_cidr("10.0.0.5/24"), "10.0.0.0/24")

    def test_invalid(self):
        with self.assertRaises(ValueError):
            _normalize_cidr("")
        with self.assertRaises(ValueError):
            _normalize_cidr("not-cidr")


class TestRoutingRuleBase(unittest.TestCase):

    def test_id_autogenerated(self):
        r = CidrRoutingRule(target_iface="awg0", cidrs=["10.0.0.0/24"])
        self.assertTrue(r.id.startswith("cidr-"))

    def test_id_explicit(self):
        r = CidrRoutingRule(target_iface="awg0", cidrs=["10.0.0.0/24"],
                            rule_id="custom-1")
        self.assertEqual(r.id, "custom-1")

    def test_invalid_iface_raises(self):
        with self.assertRaises(ValueError):
            CidrRoutingRule(target_iface="", cidrs=["10.0.0.0/24"])
        with self.assertRaises(ValueError):
            CidrRoutingRule(target_iface="bad iface", cidrs=["10.0.0.0/24"])


class TestCidrRoutingRule(unittest.TestCase):

    def test_basic(self):
        r = CidrRoutingRule(target_iface="awg0",
                            cidrs=["10.0.0.0/24", "192.168.1.0/24"])
        self.assertEqual(r.cidrs, ["10.0.0.0/24", "192.168.1.0/24"])
        self.assertEqual(r.ip_version, "auto")

    def test_empty_cidrs_fail(self):
        with self.assertRaises(ValueError):
            CidrRoutingRule(target_iface="awg0", cidrs=[])

    def test_string_cidr_coerced(self):
        r = CidrRoutingRule(target_iface="awg0", cidrs="10.0.0.0/24")
        self.assertEqual(r.cidrs, ["10.0.0.0/24"])

    def test_normalization(self):
        # 1.2.3.4 без маски → /32
        r = CidrRoutingRule(target_iface="awg0", cidrs=["1.2.3.4"])
        self.assertEqual(r.cidrs[0], "1.2.3.4/32")

    def test_ip_version_constraint(self):
        with self.assertRaises(ValueError):
            CidrRoutingRule(target_iface="awg0",
                            cidrs=["2001:db8::/32"], ip_version="v4")

    def test_cidr_families(self):
        r = CidrRoutingRule(target_iface="awg0",
                            cidrs=["10.0.0.0/24", "2001:db8::/32"])
        fams = r.cidr_families()
        self.assertEqual(fams, [("10.0.0.0/24", "v4"),
                                 ("2001:db8::/32", "v6")])

    def test_to_dict_roundtrip(self):
        r = CidrRoutingRule(target_iface="awg0", cidrs=["10.0.0.0/24"],
                            description="test", priority=5)
        d = r.to_dict()
        self.assertEqual(d["type"], "cidr")
        self.assertEqual(d["target_iface"], "awg0")
        self.assertEqual(d["cidrs"], ["10.0.0.0/24"])
        self.assertEqual(d["description"], "test")
        self.assertEqual(d["priority"], 5)


class TestDomainRoutingRule(unittest.TestCase):

    def test_basic(self):
        r = DomainRoutingRule(target_iface="awg0",
                              domains=["youtube.com", "ytimg.com"])
        self.assertEqual(r.domains, ["youtube.com", "ytimg.com"])

    def test_empty_strings_filtered(self):
        r = DomainRoutingRule(target_iface="awg0",
                              domains=["a.com", "", "  ", "b.com"])
        self.assertEqual(r.domains, ["a.com", "b.com"])

    def test_to_dict(self):
        r = DomainRoutingRule(target_iface="awg0", domains=["a.com"])
        d = r.to_dict()
        self.assertEqual(d["type"], "domain")
        self.assertEqual(d["domains"], ["a.com"])


class TestDeviceRoutingRule(unittest.TestCase):

    def test_basic(self):
        r = DeviceRoutingRule(target_iface="awg0",
                              source_ip="192.168.1.10",
                              mac="AA:BB:CC:DD:EE:FF",
                              hostname="iphone")
        self.assertEqual(r.source_ip, "192.168.1.10")
        self.assertEqual(r.mac, "AA:BB:CC:DD:EE:FF")
        self.assertEqual(r.hostname, "iphone")

    def test_to_dict(self):
        r = DeviceRoutingRule(target_iface="awg0", source_ip="10.0.0.5")
        d = r.to_dict()
        self.assertEqual(d["type"], "device")
        self.assertEqual(d["source_ip"], "10.0.0.5")


class TestRuleFromDict(unittest.TestCase):

    def test_cidr(self):
        d = {"type": "cidr", "target_iface": "awg0",
             "cidrs": ["10.0.0.0/24"]}
        r = rule_from_dict(d)
        self.assertIsInstance(r, CidrRoutingRule)

    def test_domain(self):
        d = {"type": "domain", "target_iface": "awg0",
             "domains": ["a.com"]}
        r = rule_from_dict(d)
        self.assertIsInstance(r, DomainRoutingRule)

    def test_device(self):
        d = {"type": "device", "target_iface": "awg0",
             "source_ip": "10.0.0.5"}
        r = rule_from_dict(d)
        self.assertIsInstance(r, DeviceRoutingRule)

    def test_unknown_type(self):
        with self.assertRaises(ValueError):
            rule_from_dict({"type": "wireguard", "target_iface": "awg0"})

    def test_not_dict(self):
        with self.assertRaises(ValueError):
            rule_from_dict("not-a-dict")

    def test_preserves_id(self):
        d = {"type": "cidr", "target_iface": "awg0",
             "cidrs": ["10.0.0.0/24"], "id": "preserved-id"}
        r = rule_from_dict(d)
        self.assertEqual(r.id, "preserved-id")


if __name__ == "__main__":
    unittest.main()
